kind: pipeline
type: docker
name: default

steps:
  - name: yarn install
    image: node:alpine
    commands:
      - yarn
  - name: yarn build
    image: node:alpine
    commands:
      - yarn build
  - name: notify
    image: curlimages/curl
    commands:
      - |
        curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=dbb3fa53-29f8-4394-bfa1-ecce009e8cbb' -H 'Content-Type: application/json' -d '{"msgtype": "text", "text": {"content": "ok"}}'
    when:
      status:
        - failure
        - success
