kind: pipeline
type: docker
name: default

steps:
  - name: yarn install
    image: node:alpine
    commands:
      - yarn
  - name: yarn test
    image: node:alpine
    commands:
      - yarn test
  - name: yarn build
    image: node:alpine
    commands:
      - yarn build
  - name: publish to npm
    image: node:alpine
    commands:
      - yarn publish
  - name: notify
    image: curlimages/curl
    commands:
      - |
        curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=e6ad01ff-7207-4183-abfa-4c89fa802177' -H 'Content-Type: application/json' -d '{"msgtype": "text", "text": {"content": "performance-monitoring build ok"}}'
    when:
      status:
        - failure
        - success
